Mundipagg/Resources/BaseResource.cs
Mundipagg/Resources/ChargeResource.cs
Mundipagg/Resources/Interface/IChargeResource.cs
Mundipagg/Utils/HttpClientUtil.cs
Mundipagg/Utils/IHttpClientUtil.cs
Mundipagg/Utils/RestSharpClientUtil.cs

Add idempontency key for capture charge
..

[feature] Add idempontency key for capture charge

---

Mundipagg/Models/Request/CreateAccountRequest.cs
Mundipagg/Models/Request/CreateMerchantRequest.cs
Mundipagg/Models/Request/UpdateAccountRequest.cs
Mundipagg/Models/Request/UpdateAccountStatusRequest.cs
Mundipagg/Resources/AccountResource.cs

implements status update of an account. And add the ids for account creation and merchant.

Implements status update of an account

---

Mundipagg/Models/Response/GetOrderResponse.cs
Mundipagg/Models/Response/GetSubscriptionResponse.cs
Mundipagg/Models/Webhooks/Account.cs

READY
Add missing fields is some models
- GetOrderResponse: Amount
- GetSubscriptionResponse: Plan
- webhhok Account: MerchantId

[feature] Add missing fields in account model and order subscription 

---

Mundipagg/Models/Request/UpdateMerchantRequest.cs
Mundipagg/Resources/Interface/IMerchantResource.cs
Mundipagg/Resources/MerchantResource.cs

[FEATURE] - Add endpoint to update Merchant.

---

Mundipagg/Resources/Interface/IMerchantResource.cs
Mundipagg/Resources/MerchantResource.cs

:bug: pass merchantId to route.

---

Mundipagg/Models/Request/CreateAccountRequest.cs

READY
- Add bank and gateway on create bank transfer settings request. Those fields are missing.
- Change safetypay settings prop name in create account request model

Improve bank transfer and safetypay settings request

---

Mundipagg/Models/Response/GetAccountResponse.cs

READY
- Change `SafetyPay` response prop name to `Safetypay`
- Add `Gateway` prop in safetypay settings response

[Feature] Add gateway prop and change safetypay settings response

---

Mundipagg/Models/Enums/MerchantStatusEnum.cs
Mundipagg/Models/Request/UpdateMerchantStatusRequest.cs
Mundipagg/Resources/Interface/IMerchantResource.cs
Mundipagg/Resources/MerchantResource.cs

READY
Implements update merchant status

[Feature] Implements update merchant status

---

Mundipagg/Models/Request/CreateMerchantRequest.cs
Mundipagg/Models/Response/GetMerchantResponse.cs

READY
Add missing field metadata to CreateMerchantRequest and GetMerchantResponse.

[Feature] Add field metada to merchant

---

Mundipagg/Models/Request/CreateCheckoutPaymentRequest.cs

READY
Adds the property Accepted brands on class CreateCheckoutPaymentRequest
Creates the checkout with the brands that we wish

[Feature] Adds AccepetdBrands in CheckoutPaymentRequest

---

Mundipagg/Models/Request/CreateTransferSettingsRequest.cs
Mundipagg/Models/Request/UpdateAccountRequest.cs
Mundipagg/Models/Request/UpdateAntifraudSettingsRequest.cs
Mundipagg/Models/Request/UpdateAttemptSettingsRequest.cs
Mundipagg/Models/Request/UpdateBankTransferSettingsRequest.cs
Mundipagg/Models/Request/UpdateBoletoSettingsRequest.cs
Mundipagg/Models/Request/UpdateCashSettingsRequest.cs
Mundipagg/Models/Request/UpdateCheckoutSettingsRequest.cs
Mundipagg/Models/Request/UpdateCreditCardSettingsRequest.cs
Mundipagg/Models/Request/UpdateDebitCardSettingsRequest.cs
Mundipagg/Models/Request/UpdateFacebookSettingsRequest.cs
Mundipagg/Models/Request/UpdateGeneralSettingsRequest.cs
Mundipagg/Models/Request/UpdateGuaranteedCancellationSettingsRequest.cs
Mundipagg/Models/Request/UpdateMerchantSettingsRequest.cs
Mundipagg/Models/Request/UpdateMundiPaggSettingsRequest.cs
Mundipagg/Models/Request/UpdateNotificationSettingsRequest.cs
Mundipagg/Models/Request/UpdateOrderSettingsRequest.cs
Mundipagg/Models/Request/UpdatePagarmeSettingsRequest.cs
Mundipagg/Models/Request/UpdatePagarmeTransferSettingsRequest.cs
Mundipagg/Models/Request/UpdateRenewCardSettingsRequest.cs
Mundipagg/Models/Request/UpdateSafetyPaySettingsRequest.cs
Mundipagg/Models/Request/UpdateSplitSettingsRequest.cs
Mundipagg/Models/Request/UpdateSubscriptionSettingsRequest.cs
Mundipagg/Models/Request/UpdateTransferSettingsRequest.cs
Mundipagg/Models/Request/UpdateVoucherSettingsRequest.cs
Mundipagg/Models/Request/UpdateWalletSettingsRequest.cs
Mundipagg/Models/Request/UpdateWebhookAuthenticationRequest.cs
Mundipagg/Models/Request/UpdateWebhookSettingsRequest.cs

[feature] :construction: Implementa modelos para realizar a atualização de informações de uma account.

:construction: Implementa modelos p/ update account

---

Mundipagg/Models/Request/CreateAccountRequest.cs
Mundipagg/Models/Request/CreateWebhookAuthenticationRequest.cs
Mundipagg/Models/Request/UpdateAccountRequest.cs
Mundipagg/Models/Request/UpdateMerchantSettingsRequest.cs
Mundipagg/Models/Request/UpdateWalletSettingsRequest.cs
Mundipagg/Models/Request/UpdateWebhookSettingsRequest.cs

This is a guide to use this Pull Request Template.
[feature] Implements the crazy powerful transaction search
[hotfix] Fixes login with e-mail address
Add a gif that expresses your reaction to the implemented code, make it fun
DO NOT FORGET TO REMOVE THIS BLOCK
```
READY / IN DEVELOPMENT
Describe in an objective way what has been done.
Why do you need this implementation/fix? 
How did you solve the problem? What are the main flows? Any technical information regarding infrastructure or architecture?

:construction: Corrige mapping no fluxo de UpdateMerchant/UpdateAccount

---

Mundipagg/Models/Response/GetAccountResponse.cs

```
Adds some Fields that would fix the update_account request
[feature] includes New Fields on account general settings
Add a gif that expresses your reaction to the implemented code, make it fun
```
READY 
Describe in an objective way what has been done.
Tô fix the update account mapping request
Mapping the fields
No

Inclui campos 'primary_color' e 'secundary_color'

---

Mundipagg/Models/Request/CreateAccountRequest.cs
Mundipagg/Models/Request/CreateAttemptSettingsRequest.cs
Mundipagg/Models/Request/UpdateAccountRequest.cs
Mundipagg/Models/Response/GetAccountResponse.cs

READY 
Add attempt-settings models.
To update the attempt-settings informations

[Feature] Add attempt-settings models

---

Mundipagg/Models/Request/CreateAccountRequest.cs
Mundipagg/Models/Request/CreateMerchantRequest.cs
Mundipagg/Models/Request/UpdateMerchantRequest.cs

Implements new fields on CreateAccountRequest, CreateMerchantRequest and UpdateMerchantRequest

[feature] Implements new fields on Requests

---

Mundipagg/Resources/AccountResource.cs
Mundipagg/Resources/Interface/IAccountResource.cs

READY
Add update pagarme settings method

[Feature] Add update pagarme settings method

---

Mundipagg/Models/Request/UpdateMundipaggConfigRequest.cs
Mundipagg/Models/Request/UpdatePagarmeConfigRequest.cs
Mundipagg/Resources/AccountResource.cs
Mundipagg/Resources/Interface/IAccountResource.cs

READY
Improve mundi and pagarme update config method arguments

[Feature] Improve mundi and pagarme update config method arguments

---

Mundipagg/Resources/Interface/IMerchantResource.cs
Mundipagg/Resources/MerchantResource.cs

READY / IN DEVELOPMENT
Implements update merchant settings

[feature] Implements update merchant settings

---

Mundipagg/Resources/AccountResource.cs
Mundipagg/Resources/Interface/IAccountResource.cs

[Feature] Add endpoint to patch settings in Mark1.

---

Mundipagg/Resources/CustomerResource.cs

READY 
Changed assing "query" for ListCustomers method.
The way it is, it does not filter the customers according to the parameters sent.
Added argument name (query: query).
**Before change:**
> Consult:
> Resullt:
**After change:**
> Change:
> Consult:
> Result:

[Bugfix] Fix ListCustomers method

---

Mundipagg/IMundipaggApiClient.cs
Mundipagg/Models/Request/ListPlansRequest.cs
Mundipagg/MundipaggApiClient.cs
Mundipagg/Resources/Interface/IPlanResource.cs
Mundipagg/Resources/PlanResource.cs

READY
Adds list and get plan endpoints.
This is necessary to achieve the objective of dehydrating the Atlas.
A resource has been added consuming two endpoints already existing in the API.

[feature] Adds list and get plan endpoints

---

Mundipagg/Models/Request/ListInvoicesRequest.cs

READY
* Implement new filters for invoice.
* To maintain compatibility of the filters with the features that we have in Atlas
* Implementing three new properties in the Resouce file related to invoices.
* -

[FEATURE] Implement new filters for invoice.

---

Mundipagg/Models/Request/UpdatePixSettingsRequest.cs
Mundipagg/Resources/AccountResource.cs
Mundipagg/Resources/Interface/IAccountResource.cs

READY
Includes (newly added to MK1) PIX settings update endpoint
Required for enabling/disabling PIX in Pagarme Dash
Added new method to account resource which calls the appropriate endpoint.

[Feature] Includes Pix Settings Update Endpoint

---

Mundipagg/Models/Response/GetAccountResponse.cs

READY
Adds pix settings to response
Current account response object does not contain pix settings
Included a Pix Settings member to the Account Response class

[Feature] Adds pix settings to response

---

Mundipagg/Models/Request/CreateImportRecipientRequest.cs
Mundipagg/Resources/Interface/IRecipientResource.cs
Mundipagg/Resources/RecipientResource.cs

READY
Add new import recipient endpoint.

[Feature] Implements endpoint to import recipient

---

Mundipagg.ConsoleTest/Program.cs
Mundipagg/Models/Request/CreateCaptureChargeRequest.cs
Mundipagg/Models/Request/CreateSplitOptionsRequest.cs

READY 
Adds split object on charge capture
To allow capture charge with splite rules
Adding a split object to charge capture request

[Feature] Adds pix payment method

---

Mundipagg/Models/Request/CreateAuthenticationPOIRequest.cs
Mundipagg/Models/Request/CreateCreditCardPaymentRequest.cs
Mundipagg/Models/Request/CreateDebitCardPaymentRequest.cs
Mundipagg/Models/Request/CreateDevicePOIRequest.cs
Mundipagg/Models/Request/CreateOrderRequest.cs
Mundipagg/Models/Request/CreatePOIPaymentSettingsRequest.cs
Mundipagg/Models/Request/CreatePOIPaymentSetupRequest.cs
Mundipagg/Models/Request/CreatePOIRequest.cs
Mundipagg/Models/Response/GetActionPOIInformationResponse.cs
Mundipagg/Models/Response/GetCardResponse.cs
Mundipagg/Models/Response/GetCreditCardTransactionResponse.cs
Mundipagg/Models/Response/GetPOIPaymentSettingsResponse.cs
Mundipagg/Models/Response/GetPOIPaymentSetupResponse.cs
Mundipagg/Models/Response/GetTransactionResponse.cs
Mundipagg/Resources/Interface/IOrderResource.cs
Mundipagg/Resources/OrderResource.cs

READY
Add POI properties in request and response.
To enable transactions from the physical world.
Include POI payment settings in order and add POI properties in payment node.

[Feature] Add POI contract request and response

---

Mundipagg.ConsoleTest/Program.cs
Mundipagg/Models/Request/CreateCardRequest.cs
Mundipagg/Models/Request/CreateChargeRequest.cs
Mundipagg/Models/Request/CreateCreditCardPaymentRequest.cs
Mundipagg/Models/Request/CreatePaymentRequest.cs
Mundipagg/Models/Response/GetTransactionResponse.cs

READY
Change currency from createPayment to CreateCharge.
Add JsonProperty to fields with number in name because Newtonsoft's SnakeCaseStrategy cannot handle.
Add OperationType and OperationKey to Physical World.
To enable transactions from the physical world.
Change currency from createPayment to CreateCharge.
Add JsonProperty in fields with number in name.
Add OperationType and OperationKey to Physical World.

[Feature] Update fields contract M1

---

Mundipagg/Models/Request/CreateAccountRequest.cs

READY
Fix create account model pix property
Because i did it wrong.
Changing the property name from `PixSettingsRequest` to `PixSettings`.

[Bugfix] Fix PIX settings account create property

---

Mundipagg.ConsoleTest/Program.cs
Mundipagg/Models/Request/CreateRecipientRequest.cs
Mundipagg/Models/Request/UpdateRecipientRequest.cs
Mundipagg/Models/Response/GetRecipientResponse.cs
Mundipagg/Resources/Interface/IRecipientResource.cs
Mundipagg/Resources/RecipientResource.cs

READY / IN DEVELOPMENT
We need to add a new resource to get the recipients by code
To be able to search a recipient by code 
Adding a new resource

Adds resource to get recipients by code

---

Mundipagg/Models/Request/UpdateAutomaticAnticipationSettingsRequest.cs
Mundipagg/Models/Request/UpdateBankAccountRequest.cs
Mundipagg/Models/Request/UpdateRecipientDefaultBankAccountRequest.cs
Mundipagg/Resources/Interface/IRecipientResource.cs
Mundipagg/Resources/RecipientResource.cs

READY
We included the endpoint calls for patching recipient data.
In order to enable recipient editing in dash-api.
By including missing recipient update operations to the recipient resource.

[Feature] Adds update recipient endpoints

---

Mundipagg/Models/Request/CreateCancelChargeRequest.cs
Mundipagg/Models/Request/CreateCaptureChargeRequest.cs
Mundipagg/Models/Request/CreatePOIInformationRequest.cs

READY
Add POI node in CreateCancelChargeRequest.
Add POI node in CreateCaptureChargeRequest.
To enable capture and cancel physical world charge.
Add POI node in CreateCancelChargeRequest.
Add POI node in CreateCaptureChargeRequest.

[Feature] Add POI node in cancel and capture charge

---

Mundipagg/Models/Request/UpdatePixSettingsRequest.cs
Mundipagg/Mundipagg.csproj
Mundipagg/Resources/AccountResource.cs
Mundipagg/Resources/BaseResource.cs
Mundipagg/Resources/ChargeResource.cs
Mundipagg/Resources/CustomerResource.cs
Mundipagg/Resources/Interface/IAccountResource.cs
Mundipagg/Resources/Interface/IChargeResource.cs
Mundipagg/Resources/Interface/ICustomerResource.cs
Mundipagg/Resources/Interface/IInvoiceResource.cs
Mundipagg/Resources/Interface/IMerchantResource.cs
Mundipagg/Resources/Interface/IOrderResource.cs
Mundipagg/Resources/Interface/IPlanResource.cs
Mundipagg/Resources/Interface/IRecipientResource.cs
Mundipagg/Resources/Interface/ISubscriptionResource.cs
Mundipagg/Resources/Interface/IWebhookResource.cs
Mundipagg/Resources/InvoiceResource.cs
Mundipagg/Resources/MerchantResource.cs
Mundipagg/Resources/OrderResource.cs
Mundipagg/Resources/PlanResource.cs
Mundipagg/Resources/RecipientResource.cs
Mundipagg/Resources/SubscriptionResource.cs
Mundipagg/Resources/WebhookResource.cs

READY 
Includes async implementations for all resources' methods. 
To improve the performance of the dash api by enabling async mark1 api calls.
We included a new async version of the send request alongside a new async version of every method based on the async send request.

[Feature] Adds async methods

---

Mundipagg/Models/Request/ListCustomersRequest.cs
Mundipagg/Models/Response/GetAddressResponse.cs
Mundipagg/Models/Response/GetCardResponse.cs
Mundipagg/Models/Response/GetCustomerResponse.cs

READY
Adds and fixes fields on the customer resource
- Adds the Id field in the list customers request to filter by id
- Adds birthdate field to get customers response to match current contract from Atlas
- Adds PGID and Country fields to get card response to match current contract from Atlas
- Fixes the Line1 and Line2 fields on get address response so it'll map the raw response to the correct fields.
Our team is dehydrating Atlas from the Dashboard API and the contracts need to be kept the same now that the Mark1 API is being called through this client, and the changes in this pull request reflect that.
Added or modified the fields in the appropriate classes.

[Feature] Adds fields to customer resource

---

Mundipagg/Models/Request/CreateImportRecipientRequest.cs

Adds the property to receive if the imported recipient is the default.

[Feature] Includes default recipient property when importing the recipient

---

Mundipagg/Models/Request/CreateAccountRequest.cs

Includes missing fields at CreateCheckoutSettingsRequest
Mapped the fields in the model.

✨ Includes new fields at CreateCheckoutSettingsRequest

---

Mundipagg.ConsoleTest/Program.cs
Mundipagg/Models/Request/CreateCreditCardPaymentRequest.cs
Mundipagg/Models/Request/CreateNetworkTokenRequest.cs

READY
Change to accept network token request.
This change is necessary because in the whatsapp project the card data will not be sent, the way it will be sent is using the network token.
Just including more payment method request.

[Feature] Includes network token request

---

Mundipagg/Models/Request/RetryChargeRequest.cs
Mundipagg/Resources/ChargeResource.cs
Mundipagg/Resources/Interface/IChargeResource.cs

READY
Create a new endpoint to retry a charge adding options to request.
To give a possibility to retry a charge with/without antifraud 
By adding a new endpoint.

[FEATURE] Add charge retry endpoint with configuration

---

Mundipagg/Models/Request/CreateUsageRequest.cs
Mundipagg/Resources/Interface/ISubscriptionResource.cs
Mundipagg/Resources/SubscriptionResource.cs

Adds amount property to create usage request

✨ Adds amount property to create usage request

---

Mundipagg/Models/Request/CreateAuthenticationPOIRequest.cs

READY
Split KSN on DerivationIdentification and EncryptedKey fields, in some cases we will need the field splited into two fields
To integrate with another gateway that require splited fields
Changing the request contract

[Feat] Split KSN on DerivationIdentification and EncryptedKey fields

---

Mundipagg/Models/Response/GetSubscriptionResponse.cs

READY 
Add an info "status reason" on subscription
To inform client the reason "Chargeback" on subscription. 
Including StatusReason property in GetSubscriptionResponse.

[FEATURE] Status Reason on Subscription

---

Mundipagg/Resources/AccountResource.cs
Mundipagg/Resources/Interface/IAccountResource.cs

READY
To be able to access the endpoint with the correct request body type
Because the request was waiting for an inconsistent type
Just changing the request type from UpdateCash to UpdateAntifraudSettings

:bug: Fix model of request received by UpdateAntifraudSettings method

---

Mundipagg/Models/Request/CreatePOIPaymentSetupRequest.cs

READY 
Adding Amount property to CreatePOIPaymentSetupRequest model
It is needed for a new feature
By adding a property to a class

[feature] Adding new property to an existing model

---

Mundipagg/Models/Request/CreateDevicePOIRequest.cs
Mundipagg/Models/Request/CreatePOIPaymentSetupRequest.cs
Mundipagg/Models/Request/CreatePOIRequest.cs

```
This is a guide to use this Pull Request Template.
[feature] Implements the crazy powerful transaction search
[hotfix] Fixes login with e-mail address
Add a gif that expresses your reaction to the implemented code, make it fun
DO NOT FORGET TO REMOVE THIS BLOCK
```
READY / IN DEVELOPMENT
Describe in an objective way what has been done.
Why do you need this implementation/fix? 
How did you solve the problem? What are the main flows? Any technical information regarding infrastructure or architecture?

Merge with Master
